### ISSUE TITLE
asdf install mysql version not working

### ISSUE THREAD

**Issue by execb5** [iroddis/asdf-mysql#8] opened 2021-04-23 17:51 UTC
Hello!

I'm trying to simply install mysql using asdf and it doesn't work. I get logs below and that's it.
`asdf list mysql` returns nothing after that.

I'm on mac os big sur, I tried to install both 5.6.51 and 8.0.24 with no results.

Does anyone can help me figure out what could be wrong?

Thanks!

```
❯ asdf install mysql 5.6.51
+ set -e
++ echo 5.6.51
++ cut -d. -f1
+ MAJOR=5
++ echo 5.6.51
++ cut -d. -f2
+ MINOR=6
++ mktemp -d
+ tmp_download_dir=/var/folders/xh/r0bn7qfj4k97v0t8ybqd091r0000gp/T/tmp.gkGcP6EL
+ case "$(uname -s)" in
++ uname -s
+ FILE='mysql-5.6.51-macos10*'
+ rsync -zarv '--include=*/' '--include=*.gz' '--include=*.xz' '--exclude=*' 'rsync://rsync.mirrorservice.org/ftp.mysql.com/Downloads/MySQL-5.6/mysql-5.6.51-macos10*' /var/folders/xh/r0bn7qfj4k97v0t8ybqd091r0000gp/T/tmp.gkGcP6EL/.
-----------------------------------------------------------------------------
Welcome to the University of Kent's UK Mirror Service.

More information can be found at our web site: https://www.mirrorservice.org/
Please send comments or questions to help@mirrorservice.org.
-----------------------------------------------------------------------------

receiving file list ... done

sent 39 bytes  received 17 bytes  22.40 bytes/sec
total size is 0  speedup is 0.00
```

**Comment by faelin** [comment] 2021-04-27 20:59
bump (same result)

**Comment by faelin** [comment] 2021-04-27 21:23
@execb5 I have created PR #9 to address this issue. Please feel free to source from my fork until such time as the PR is completed.

**Comment by iroddis** [comment] 2021-04-27 21:41
Merged #9 , thanks for the PR.

**Closed as completed** 2021-04-28 13:51 UTC

**Comment by execb5** [comment] 2021-04-28 14:07
For me it's still not working.
I'm getting the same behavior. I even went to the plugin installation folder the check if my plugin was updated correctly and it is.

**Comment by limouren** [comment] 2021-05-14 08:42
@iroddis I can confirm that it is not working on macOS 11.2.3:

```
❯ asdf install mysql 5.7.34
-----------------------------------------------------------------------------
Welcome to the University of Kent's UK Mirror Service.

More information can be found at our web site: https://www.mirrorservice.org/
Please send comments or questions to help@mirrorservice.org.
-----------------------------------------------------------------------------

receiving file list ... done

sent 39 bytes  received 17 bytes  12.44 bytes/sec
total size is 0  speedup is 0.00
```

**Comment by limouren** [comment] 2021-05-14 08:53
Seems they don't have macos binary for 5.6, 5.7 and 6... https://www.mirrorservice.org/sites/ftp.mysql.com/Downloads

---

Update: They have a binary for 5.7.31, and `asdf install mysql 5.7.31` works for me

**Comment by faelin** [comment] 2021-05-14 14:03
[Stack Exchange: What happened to MySQL 6 & 7?](https://dba.stackexchange.com/questions/207506/what-happened-to-mysql-6-7)

Additionally, you can see in the official MySQL archives that the 5.6 version never had a MacOS X binary: https://downloads.mysql.com/archives/community/

Edit: Homebrew is able to download MySQL@5.6 [directly from dev.mysql.com](https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.51.tar.gz) in an uncompiled form, and subsequently compiles it. In a future fork, I will attempt to replicate this behavior for ASDF.
